02-02 15:04:56 os_reststack_manager.app ERROR    Exception on /tenant/1 [GET]
Traceback (most recent call last):
  File "/home/niedbalski/src/pet/os-reststack-manager/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/niedbalski/src/pet/os-reststack-manager/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/niedbalski/src/pet/os-reststack-manager/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/niedbalski/src/pet/os-reststack-manager/env/local/lib/python2.7/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/niedbalski/src/pet/os-reststack-manager/env/local/lib/python2.7/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/home/niedbalski/src/pet/os-reststack-manager/os_reststack_manager/app/tenant_manager.py", line 32, in authenticate
    except jwt.DecodeError:
AttributeError: 'module' object has no attribute 'DecodeError'
